development:
  secret_key_base: fc10280147ee153d098675a4275356656728b8606b6c2c8e9070f6c4af3a27885d66592af99cfc71ff6b76c1734c0b5044ad2fed5d1a470a0ce5258942bfb31d
  shortener_api_key: <%= ENV.fetch('SHORTENER_API_KEY', nil) %>
  shortener_root_redirect_url: <%= ENV.fetch('SHORTENER_ROOT_REDIRECT_URL', nil) %>

test:
  secret_key_base: fc10280147ee153d098675a4275356656728b8606b6c2c8e9070f6c4af3a27885d66592af99cfc71ff6b76c1734c0b5044ad2fed5d1a470a0ce5258942bfb31d
  shortener_api_key: <%= ENV.fetch('SHORTENER_API_KEY', nil) %>
  shortener_root_redirect_url: <%= ENV.fetch('SHORTENER_ROOT_REDIRECT_URL', nil) %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  shortener_api_key: <%= ENV.fetch('SHORTENER_API_KEY', nil) %>
  shortener_root_redirect_url: <%= ENV.fetch('SHORTENER_ROOT_REDIRECT_URL', nil) %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
